apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dns
  # namespace: opscool-mid-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-dns
  template:
    metadata:
      labels:
        app: flask-dns
    spec:
      containers:
      - name: flask-dns
        image: idobaram/mid-course-app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000